name: OBMetaProducerBungee
main: net.obmc.OBMetaProducerBungee.OBMetaProducer
version: 0.1
api-version: "1.21"
author: Fahrenheit451
description: Gather BungeeCord events into file for monitoring
website: http://ob-mc.net